### ISSUE TITLE
Consider integrating Conan as the 1st-class dependency manager

### ISSUE THREAD

**Issue by jondo2010** [ja11sop/cuppa#29]

**Comment by ja11sop** [comment]
You mean [https://conan.io/](https://conan.io/) for anyone who stumbles across this and isn't sure what Conan is. I'll look into how some sort of support might be added for Conan. Though I do think Conan tries to solve the problem Cuppa addresses in a different way there may be some useful overlapping compatibilities that can be exposed.

**Comment by ja11sop** [comment]
## Reframe (from open-issues triage)

Original title: “Consider integrating Conan as the 1st-class dependency manager.”

**Recommended product framing:** Cuppa remains the **build orchestrator**. Conan is an optional **package supply chain** — a way to obtain third-party libraries and inject their flags into Cuppa envs. Do **not** make Conan drive `cuppa.run()`, replace variants/toolchains, or become mandatory.

### Why this helps adoption

| Factor | Assessment |
|--------|------------|
| Market reach | Conan (with vcpkg) is a mainstream C++ package ecosystem; many libraries ship recipes (fmt, spdlog, OpenSSL, Boost, Qt, …). |
| Cuppa gap today | Strong at orchestration (variants, toolchains, tests, coverage, modules). Package story is **GitLab generic registry** + **location/git** deps — excellent for private orgs, weak for “pull common third-party libs like everyone else”. |
| Adoption friction | New users ask “how do I get Boost/fmt/…?” Location deps imply fetch/build; GitLab packages need your own publishing pipeline. Conan lowers that barrier. |
| Competitive context | CMake+Conan, Meson+PkgConfigDeps, etc. already combine a build system with a package manager. Cuppa without a mainstream package *source* looks niche even when the SCons API is better. |
| Identity risk | “1st-class dependency manager” wording risks Cuppa becoming a Conan front-end. Keep GitLab `package_dependency` and `location_dependency` first-class; Conan is opt-in. |

### Explicit non-goals

- Requiring Conan to use Cuppa.
- Replacing `cuppa.run()` / SCons with `conan build` as the primary driver.
- Vendoring ConanCenter or competing with Conan as a package host.
- Supporting Conan 1.x as a primary target (Conan 2 only unless a thin shim appears later).

---

## Approaches (explore before locking)

Three consumer strategies fit Cuppa. They can be phased; they are not mutually exclusive forever.

```mermaid
flowchart LR
  subgraph cuppaOrch [Cuppa orchestrator]
    variants[dbg_rel_cov]
    toolchains[gcc_clang_vc]
    buildWith[BuildWith]
  end
  subgraph conanSupply [Conan supply chain]
    install[conan install]
    gens[generators folder]
  end
  buildWith --> install
  install --> gens
  gens --> flags[CPPPATH_LIBPATH_LIBS]
  flags --> buildWith
  variants --> install
  toolchains --> install
```

### Approach A — `PkgConfigDeps` (recommended first slice)

**Idea:** `conan install` with generator `PkgConfigDeps`. Cuppa sets `PKG_CONFIG_PATH` to the generators folder and turns `.pc` files into SCons flags (`ParseFlags` / `pkg-config --cflags --libs`).

| Pros | Cons |
|------|------|
| Battle-tested Conan 2 path (also used by Meson) | Windows needs `pkg-config`/`pkgconf` available |
| Language-agnostic; no CMake in Cuppa | Component-heavy packages need care with `.pc` names |
| Fits SCons `MergeFlags` naturally | Less IDE-oriented than CMakeDeps |

**Best fit for Cuppa’s SCons model.**

### Approach B — Custom JSON / “CuppaDeps” generator

**Idea:** Small Conan generator (or post-process of Conan’s dependency graph) that writes a stable JSON file Cuppa reads: includes, libdirs, libs, defines, system libs per package/component.

| Pros | Cons |
|------|------|
| Exact control; no pkg-config on Windows | Must maintain generator against Conan 2 APIs |
| Clear unit-test surface | Duplicates what PkgConfigDeps already encodes |
| Easy offline reuse of a frozen generators tree | |

**Good Phase 2** if PkgConfigDeps proves awkward on MSVC CI, or for a pure-Python path with no pkg-config.

### Approach C — Bring-your-own `conan install`

**Idea:** User (or CI) runs `conan install` beforehand. Cuppa only **consumes** an existing generators/output folder (like `--offline` for registries).

| Pros | Cons |
|------|------|
| Clear separation; easy to debug Conan alone | Extra step for newcomers |
| Matches “Cuppa does not own the lockfile workflow” | Easy to get settings mismatch (Debug vs dbg) |

**Should be supported regardless** as `--conan-install-folder=` / “reuse existing” mode.

### Approaches deferred / avoided

| Approach | Why defer |
|----------|-----------|
| Drive builds via `CMakeDeps` + invoke CMake from Cuppa | Pulls CMake into the critical path; Cuppa is SCons-first |
| Shell out to parse CMake targets | Fragile |
| Conan as the only dependency API | Conflicts with location/GitLab package identity |

---

## Mapping Cuppa → Conan settings

| Cuppa | Conan 2 (sketch) |
|-------|------------------|
| Toolchain `gcc` / `clang` / `vc` | `settings.compiler` (+ version when known) |
| Host/target arch | `settings.arch` |
| Variant `dbg` | `settings.build_type=Debug` |
| Variant `rel` | `settings.build_type=Release` |
| Variant `cov` | Prefer `Debug` (or document RelWithDebInfo); coverage flags still come from Cuppa’s cov variant, not Conan |
| OS | `settings.os` from `cuppa.build_platform` |

**Fingerprint:** cache `conan install` outputs under something like `_cuppa/conan/<settings_hash>/` (or beside `_build`) so switching `--dbg` ↔ `--rel` or gcc ↔ clang does not clobber each other.

**Concurrency:** one install per fingerprint; safe under `--parallel` builds that share the same fingerprint (install before graph execute, or SCons `Command` with a shared lock/target).

---

## Code sketches (illustrative, not final API)

### Sketch 1 — Declaring Conan deps in `sconstruct`

```python
import cuppa

# Option A: inline requires (simple apps)
Fmt = cuppa.conan_dependency(
    'fmt',
    requires=['fmt/11.0.2'],
    # generators default to PkgConfigDeps (+ VirtualRunEnv if needed)
)

# Option B: project conanfile (lockfile-friendly)
ThirdParty = cuppa.conan_deps(
    name='conan',
    conanfile='conanfile.txt',   # or conanfile.py
    # install_folder=None → managed under _cuppa/conan/<fingerprint>
)

cuppa.run(
    dependencies=[Fmt],          # or [ThirdParty]
    default_dependencies=['fmt'],
)
```

```text
# conanfile.txt
[requires]
fmt/11.0.2
spdlog/1.14.1

[generators]
PkgConfigDeps
```

### Sketch 2 — Using in a sconscript (unchanged Cuppa shape)

```python
Import('env')

env.BuildWith('fmt')   # or 'conan' for the whole graph
env.Build('app', ['main.cpp'])
# CPPPATH / LIBS already enriched for this variant env
```

### Sketch 3 — Dependency `__call__` (PkgConfigDeps path)

```python
def __call__(self, env, toolchain, variant):
    fingerprint = self._settings_fingerprint(env, toolchain, variant)
    install_dir = self._ensure_conan_install(fingerprint)  # runs or reuses

    pc_path = os.path.join(install_dir, 'generators')  # layout TBD
    env.PrependENVPath('PKG_CONFIG_PATH', pc_path)

    for pkg in self._pkg_config_names:  # e.g. ['fmt']
        flags = env.ParseFlags(
            subprocess.check_output(['pkg-config', '--cflags', '--libs', pkg], text=True)
        )
        env.MergeFlags(flags)
```

### Sketch 4 — Reuse existing install (Approach C)

```python
ThirdParty = cuppa.conan_deps(
    name='conan',
    conanfile='conanfile.txt',
    install_folder=os.environ.get('CONAN_OUTPUT_FOLDER'),  # CI pre-warmed
    install=False,  # never invoke conan; fail if generators missing
)
```

CLI sketch (optional later):

```sh
cuppa -D --dbg --conan-install-folder=_cuppa/conan/abc123
```

### Sketch 5 — Pip plugin packaging (same discovery story as #27)

A thin PyPI package can expose a pre-canned Conan graph as a Cuppa dependency via `cuppa.dependency.plugins`, so apps only need:

```text
# requirements.txt
cuppa
cuppa-conan-fmt-example==…
```

```ini
# that package's setup.cfg
[options.entry_points]
cuppa.dependency.plugins =
    fmt = cuppa_conan_fmt:FmtDependency
```

Core Cuppa still owns `conan_dependency` / install fingerprinting; the plugin only declares requires + name.

### Sketch 6 — Fail clearly

```python
if not shutil.which('conan'):
    raise SCons.Errors.StopError(
        "conan_dependency requires the 'conan' CLI (Conan 2). "
        "Install it or remove the dependency."
    )
# Mismatched build_type / compiler: StopError with fingerprint + conan profile dump
```

---

## Trade-offs summary

| Topic | Choice leaning | Trade-off |
|-------|----------------|-----------|
| Identity | Consumer only | Less “batteries for everything”, clearer product |
| Generator | PkgConfigDeps first | Weaker on Windows without pkgconf; mitigations: ship docs, or Phase 2 JSON deps |
| When to install | Lazy per fingerprint at dependency apply | First configure slower; subsequent builds cached |
| Lockfiles | Honour `conan.lock` when present | Users must learn Conan lock workflow for reproducibility |
| `cov` variant | Map to Debug + Cuppa cov flags | Conan packages are not “coverage builds” of third-party code by default |
| Parallelism | Shared install target per fingerprint | Must not run concurrent `conan install` into the same folder |
| Offline | Reuse install folder / Conan cache | Aligns with Cuppa `--offline` spirit but Conan has its own cache |

---

## Implementation phases

### Phase 0 — Spike (short)

1. Manual spike: `conanfile.txt` + `PkgConfigDeps` + tiny SCons/`cuppa` script that `MergeFlags` from `pkg-config`.
2. Record Windows story (pkgconf vs skip).
3. Decide Phase 1 generator (A vs B) with evidence.

### Phase 1 — MVP consumer

1. `cuppa.conan_deps(conanfile=…)` and/or `cuppa.conan_dependency(name, requires=[…])`.
2. Settings fingerprint + install cache directory.
3. Apply via `BuildWith` using PkgConfigDeps (or chosen spike winner).
4. Unit tests with mocked `conan` / fixture generators folder; one optional integration marked skip-without-conan.
5. Docs: packages/dependencies page + non-goals; ROADMAP IDs updated.

### Phase 2 — Hardening

1. Explicit reuse of pre-built install folders.
2. Better MSVC path (JSON CuppaDeps or documented pkgconf).
3. Lockfile / `conan install --locked` guidance.
4. Optional pip-plugin example.

### Phase 3 — Nice-to-have

1. Richer component selection APIs (`use_libs`-style).
2. Interaction notes with modules BMI packages (separate supply chains).

---

## Acceptance criteria (Phase 1)

- [ ] Public API to declare Conan-backed deps without making Conan mandatory for other projects.
- [ ] `env.BuildWith(...)` injects includes/libs for the active toolchain/variant.
- [ ] Install outputs cached per settings fingerprint; second build does not re-download unnecessarily.
- [ ] Missing `conan` CLI fails with `StopError` and a clear message.
- [ ] Docs state consumer-only framing and point at location/GitLab packages as peers.
- [ ] ROADMAP **Conan consumer integration** section reflects shipped vs remaining work.
- [ ] Issue #29 updated with this plan (reframe title/body as needed).

## References

- Triage rationale: open-issues triage plan Stage 0b
- Peers: `cuppa.location_dependency`, `cuppa.package_dependency` (GitLab), Boost package helpers
- Plugin discovery: `cuppa.dependency.plugins` in `construct.py` (same pattern as #27 Tool wrappers)
- Conan 2: `PkgConfigDeps`, profiles/settings, lockfiles
- Related roadmap: SCons Tool dependencies (#27); optional later vcpkg if demand appears

**Comment by ja11sop** [comment]
# Conan plan gap review and revised approach

Source reviewed: [CONAN_CONSUMER_PLAN.md](CONAN_CONSUMER_PLAN.md), [ROADMAP.md](ROADMAP.md) Conan section, [build_with.py](cuppa/methods/build_with.py), package/location dependency factories, Conan 2 docs (`SConsDeps`, `PkgConfigDeps`).

## Critical gap: generator choice

Conan 2 already provides **`conan.tools.scons.SConsDeps`**, which writes `SConscript_conandeps` with `CPPPATH`, `LIBPATH`, `LIBS`, `CPPDEFINES`, `CCFLAGS`, `CXXFLAGS`, `LINKFLAGS`, `FRAMEWORKS`, etc., intended for `env.MergeFlags(...)`.

The current plan leads with **PkgConfigDeps** and treats a custom JSON generator as Phase 2. That underuses the native SCons integration and keeps an unnecessary Windows `pkg-config` dependency for the happy path.

**Locked decision for Phase 1:** use **`SConsDeps`** as the primary generator. Keep PkgConfigDeps only as a documented fallback / non-goal for MVP. Drop “custom CuppaDeps JSON” from the critical path unless SConsDeps proves insufficient in the spike.

```mermaid
flowchart TD
  buildWith[BuildWith conan dep]
  fingerprint[Settings fingerprint]
  install[conan install SConsDeps]
  sconscript[SConscript_conandeps]
  merge[env.MergeFlags]
  buildWith --> fingerprint
  fingerprint --> install
  install --> sconscript
  sconscript --> merge
```

Consumer load sketch (replaces pkg-config sketch in the plan):

```python
info = SConscript(os.path.join(install_dir, 'SConscript_conandeps'))
env.MergeFlags(info['conandeps'])   # or info['fmt'] for one require
```

## Other gaps to fold into the plan before coding

### Lifecycle and Cuppa integration

- **When `conan install` runs:** `BuildWith` calls dependency `__call__` during **SConscript evaluation** ([build_with.py](cuppa/methods/build_with.py)), including `default_dependencies` in `init_env_for_variant`. Install is therefore configure-time Python work, not a SCons builder node—document that, and use process-safe caching (file lock / “done” marker per fingerprint) so parallel SCons workers / multi-sconscript `BuildWith` do not race.
- **One graph vs many names:** Clarify MVP API: prefer **one** `conan_deps(conanfile=…)` dependency that applies the whole graph via `info['conandeps']`, plus optional per-require merge (`info['fmt']`). Avoid N separate `conan install`s for N `conan_dependency('fmt')` entries unless installs share one fingerprint cache keyed by the full requires set.
- **Identity for CreateVersion:** Plan should state whether Conan deps expose `version` / `repository` / `revisions` (even if “N/A” / package ref strings) so version.cpp stays consistent with other deps.

### Settings fidelity (under-specified today)

Expand Cuppa → Conan mapping beyond build_type/compiler/os/arch:

- **`compiler.version`** from Cuppa toolchain (e.g. gcc15 / clang21), not just family name.
- **`compiler.cppstd`** from Cuppa dialect / `StdCpp` / toolchain default (`cxx2c`, `c++20`, …).
- **`compiler.libcxx`** when Clang uses `--clang-stdlib=libc++` vs libstdc++.
- **MSVC** runtime / toolset if Conan requires them (`compiler.runtime`, compiler version from `vc145`).
- **`options`:** at least document `*:shared=True/False`; MVP can default to Conan package defaults and allow override via conanfile.
- **Cross / `target_architectures`:** Phase 1 = host-only; call out cross as later (build vs host profiles).

### Runtime and tests

- **Shared libs at test/run time:** linking is not enough for `--test` / `--run`. Plan should include applying Conan **VirtualRunEnv** (or appending package `bindirs`/`libdirs` to `env['ENV']['PATH']` / `LD_LIBRARY_PATH` / `DYLD_LIBRARY_PATH`) when actions run.
- **Header-only packages:** still work via SConsDeps includes; note no LIBS.

### Cuppa flags and offline

- Interaction with **`--offline` / `--develop`:** Conan has its own cache; define behaviour: `--offline` means “do not call remotes / fail if install needed”, not “ignore Conan”. `--develop` does not substitute Conan packages (same honesty as GitLab packages).
- **Remotes / auth:** `CONAN_LOGIN_USERNAME` / token env vars; fail clearly on 401/missing package.
- **Lockfiles:** if `conan.lock` beside conanfile, pass `--lockfile` / locked install; else warn that builds are not pinned.

### API and docs gaps

- Resolve dual sketch APIs: ship **`conan_deps(conanfile=…)`** as primary; **`conan_dependency(name, requires=[…])`** as sugar that writes a transient conanfile or embeds requires into the same install machinery with one shared cache key.
- **`tool_requires`:** out of scope for MVP (SConsDeps historically weak here); document limitation (e.g. protobuf plugins).
- **Editable / local recipes:** later.
- **Conflict with user `generate()`** in `conanfile.py`: Cuppa should pass `--generator=SConsDeps` on the CLI (or ensure generators list includes it) without fighting a full custom `generate()`—document “prefer conanfile.txt for Cuppa-managed install” or “must include SConsDeps”.
- **Link flag routing:** Cuppa distinguishes `LIBS` / `STATICLIBS` / `DYNAMICLIBS`; SConsDeps typically fills `LIBS`—document that MVP uses `MergeFlags` as Conan emits, and richer routing is Phase 2.
- **Modules BMI packages:** keep as separate supply chain (already noted); no Conan BMI story in MVP.

### Testing gaps

- Unit: mock install dir containing a minimal `SConscript_conandeps` fixture; assert `MergeFlags` keys applied.
- Integration: `@pytest.mark.skipif(not shutil.which('conan'))` + network-or-cache; Linux primary; Windows CI only if Conan+compiler profile is maintainable (otherwise document skip).
- Negative: missing conan CLI → `StopError`; corrupt/missing `SConscript_conandeps` → `StopError`.

### Security / trust

- Running `conan install` executes recipe code from remotes—brief docs warning (same class of risk as fetching location deps).

## Revised Phase 0 / 1 (after plan doc update)

1. **Update** [CONAN_CONSUMER_PLAN.md](CONAN_CONSUMER_PLAN.md) and [ROADMAP.md](ROADMAP.md) Conan IDs: primary generator `SConsDeps`; PkgConfigDeps demoted; list the gaps above as explicit decisions.
2. **Spike:** `conanfile.txt` with `fmt`, `generators = SConsDeps`, `conan install`, load `SConscript_conandeps` in a tiny Cuppa/`scons` script, `MergeFlags`, compile a hello that `#include <fmt/core.h>`. Record compiler settings flags used.
3. **Implement MVP** in-tree: e.g. [cuppa/build_with_conan.py](cuppa/build_with_conan.py) (name TBD) + export from [cuppa/__init__.py](cuppa/__init__.py); fingerprint + cache under download/cache roots; `BuildWith` apply; unit fixture tests; docs on [dependencies.adoc](docs/modules/ROOT/pages/dependencies.adoc); CHANGELOG.

## Out of scope for first implementation PR

- Custom JSON CuppaDeps generator
- PkgConfigDeps as default
- Cross-compilation profiles
- `tool_requires` / code generators
- Pip plugin example package (docs only is enough)
- Making Conan mandatory or replacing GitLab/location deps

**Comment by ja11sop** [comment]
# Conan package publishing for Cuppa

Producer-side Conan 2 support: package Cuppa-built libraries and upload them to a Conan remote, without making Conan the build orchestrator.

Related: [`CONAN_CONSUMER_PLAN.md`](CONAN_CONSUMER_PLAN.md), [`ROADMAP.md`](ROADMAP.md), GitHub [#29](https://github.com/ja11sop/cuppa/issues/29).

## Goal

Teams with an internal Conan registry (GitLab Conan, Artifactory, …) can build with Cuppa and publish binaries that other Cuppa projects consume via existing `conan_deps` / `conan_dependency` — without CMake.

## Locked approach

**Cuppa builds first**, then a Conan recipe **packages prebuilt files** (`conan export-pkg`) and optionally **`conan upload`s**. Parallel to GitLab generic `PublishPackage`, not a replacement.

Rejected: `conan create` where `build()` runs Cuppa/SCons.

## API

```python
from cuppa.package_managers.conan import ConanPackagePublisher

publisher = ConanPackagePublisher(
    env,
    name='mylib',
    version='1.2.3',
    user='myorg',       # optional
    channel='stable',   # optional
    remote='gitlab',    # required for upload
    remote_url=None,    # optional: add remote if missing
    source_include_dir='include',
    source_lib_dir=env['abs_final_dir'],
    libs=None,          # optional; auto-detect from lib dir
)

env.PublishPackage( built_lib, publisher )
# cuppa -D --rel --publish-package
```

Reuse `--publish-package`. Auth via `CONAN_LOGIN_USERNAME` / `CONAN_PASSWORD` (CI: `ci_user` + `CI_JOB_TOKEN`); Cuppa does not store tokens.

## Settings

Reuse `conan_settings_for()` / `settings_to_cli()` from `cuppa/build_with_conan.py` so package IDs match consumer installs.

## Offline

`--offline`: `export-pkg` may still update the local Conan cache; **upload is skipped** (or fails clearly if forced). Remotes are not contacted for upload.

## Phases

| Phase | Status |
|-------|--------|
| 0 Spike | Done — export-pkg + consumer round-trip via local cache |
| 1 MVP | Done — `ConanPackagePublisher`, unit/integration tests, packages docs |
| 2 Later | Hand-written conanfile override, shared option, requires, components, modules/BMI |

## Caveats

GitLab’s Conan 2 registry may still be marked under development; prefer documenting “any Conan 2 remote,” with GitLab as one target.

**Comment by ja11sop** [comment]
Closed by #124
